# NOTE: You must disable the banner and the console logging
# to allow the STDIO transport to work !!!
spring:
  main:
    banner-mode: off
#    web-application-type: reactive
  ai:
    mcp:
      server:
        name: my-weather-server
        version: 0.0.1
        type: sync
        enabled: true
        instructions: This reactive server provides weather information tools and resources
        sse-endpoint: /sse
        sse-message-endpoint: /mcp/message
        base-url: /api/v1
        capabilities:
          tool: true
          resource: true
          prompt: true
          completion: true
        stdio: false

# logging.pattern.console=
logging:
  charset:
    console: utf-8
  level:
    root: info
    org.springframework: debug
