/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "omnilink"

include(
    "omnilink-bridge",
    "omnilink-flywise",
    "omnilink-regsvr",
//    "omnilink-manual-sample"
)

include(":omnilink-flywise:omnilink-flywise-stock")
include(":omnilink-flywise:omnilink-flywise-weather")
include(":omnilink-bridge:omnilink-bridge-javaseeker")
include(":omnilink-regsvr:omnilink-regsvr-nacos")

// Add manual sample submodules
//include(":omnilink-manual-sample:mcp-stock-client")
//include(":omnilink-manual-sample:mcp-weather-client")
//include(":omnilink-manual-sample:mcp-javaseeker-client")
//include(":omnilink-manual-sample:mcp-github")
//include(":omnilink-manual-sample:mcp-filesystem")

project(":omnilink-flywise:omnilink-flywise-stock").name = "omnilink-flywise-stock"
//project(":omnilink-flywise:omnilink-flywise-weather").projectDir = file("omnilink-flywise/omnilink-flywise-weather")
//project(":omnilink-bridge:omnilink-bridge-javaseeker").projectDir = file("omnilink-bridge/omnilink-bridge-javaseeker")
//project(":omnilink-regsvr:omnilink-regsvr-nacos").projectDir = file("omnilink-regsvr/omnilink-regsvr-nacos")
//
//// Set manual sample submodule paths
//project(":omnilink-manual-sample:mcp-stock-client").projectDir = file("omnilink-manual-sample/mcp-stock-client")
//project(":omnilink-manual-sample:mcp-weather-client").projectDir = file("omnilink-manual-sample/mcp-weather-client")
//project(":omnilink-manual-sample:mcp-javaseeker-client").projectDir = file("omnilink-manual-sample/mcp-javaseeker-client")
//project(":omnilink-manual-sample:mcp-github").projectDir = file("omnilink-manual-sample/mcp-github")
//project(":omnilink-manual-sample:mcp-filesystem").projectDir = file("omnilink-manual-sample/mcp-filesystem")
