/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "ominilink"
include(":ominilink-flywise-stock")
include(":ominilink-bridge")
include(":ominilink-flywise-weather")
include(":ominilink-flywise")
include(":ominilink-bridge-javaseeker")
project(":ominilink-flywise-stock").projectDir = file("ominilink-flywise/ominilink-flywise-stock")
project(":ominilink-flywise-weather").projectDir = file("ominilink-flywise/ominilink-flywise-weather")
project(":ominilink-bridge-javaseeker").projectDir = file("ominilink-bridge/ominilink-bridge-javaseeker")
