
spring:
  main:
    web-application-type: reactive
    banner-mode: off
  ai:
    mcp:
      server:
        name: my-stock-server
        version: 0.0.1
        type: async
        enabled: true
        stdio: false

# NOTE: You must disable the banner and the console logging 
# to allow the STDIO transport to work !!!
server:
  port: 8080
