spring:
  application:
    name: mcp-nacos-client-example
  ai:
    openai:
      api-key: ${AI_DASHSCOPE_API_KEY}
      base-url: https://api.deepseek.com
      chat:
        options:
          model: deepseek-reasoner
    mcp:
      client:
        enabled: true
        name: my-mcp-client
        version: 1.0.0
        request-timeout: 30s
        type: ASYNC  # or ASYNC for reactive applications
    alibaba:
      mcp:
        nacos:
          namespace: 4ad30fba-bd2c-4c88-b9ac-a22312c682b7
          server-addr: 127.0.0.1:28848
          username: mcp
          password: ${MCP_PASSWD}
#          registry:
#            enabled: true
#            service-group: DEFAULT_GROUP
#            service-name: public

          client:
            enabled: true
            sse:
              connections:
                server1:
                  # {spring.ai.mcp.server.name}::{spring.ai.mcp.server.version}
                  service-name: webmvc-mcp-server::1.0.0
#                  version: 1.0.0
  main:
    web-application-type: none

# 调试日志
logging:
  level:
    com.alibaba.nacos: debug
    io.modelcontextprotocol: debug