/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("buildlogic.java-conventions")
}

dependencies {
    api(libs.org.springframework.ai.spring.ai.mcp.server.spring.boot.starter)
    api(libs.org.springframework.spring.web)
}

description = "ominilink-flywise-stock"
