/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    // id("buildlogic.java-conventions")
    alias(libs.plugins.org.springframework.boot)
}

dependencies {
    // api(libs.spring.ai.mcp.server.webflux.spring.boot.starter) // Removed MCP Starter
    // api(libs.org.springframework.spring.web) // Replaced by spring-boot-starter-web
    implementation(libs.org.springframework.boot.spring.boot.starter)
    implementation(libs.org.springframework.boot.spring.boot.starter.web)
//    implementation(libs.spring.ai.starter.model.openai)
    implementation(libs.spring.ai.mcp.server.webmvc)
    implementation(libs.spring.ai.mcp.server.webflux)
    implementation(libs.spring.boot.starter.logging)
    implementation(libs.spring.boot.starter.actuator)
    // implementation("org.springframework.ai:spring-ai-mcp-server-spring-boot-starter")
}

description = "omnilink-flywise-weather"

tasks.named<Test>("test") {
    enabled = false
}
