/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    alias(libs.plugins.org.springframework.boot)
}

dependencies {
    implementation(libs.spring.ai.mcp.server.webflux)
    implementation(libs.spring.boot.starter.logging)
    implementation(libs.spring.boot.starter.actuator)
}

description = "omnilink-flywise-weather"

tasks.named<Test>("test") {
    enabled = false
}
