/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
    // Ensure access to version catalog if not automatically available in buildSrc plugins.
    // This might require further setup in buildSrc/build.gradle.kts if libs isn't found.
    // For now, assuming it can be made available or accessed correctly.
}

// Repositories should be defined in settings.gradle.kts, removing from here.

// Group and version are set in root build.gradle.kts for allprojects.
// Java compatibility is set in root build.gradle.kts for subprojects.

dependencies {
    // Accessing libs from a convention plugin in buildSrc.
    // Ensure 'libs' is accessible. If not, might need 'rootProject.libs' or other context.
    // Programmatic access to the version catalog for use in buildSrc
    val libsCatalog = project.extensions.getByType(org.gradle.api.artifacts.VersionCatalogsExtension::class.java).named("libs")

    implementation(platform(libsCatalog.findLibrary("spring-boot-dependencies").get())) // Corrected alias
    implementation(platform(libsCatalog.findLibrary("spring-ai-bom").get())) // Corrected alias
}


publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
    // Java version and -parameters are handled by the root build.gradle.kts's subprojects block
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
