spring:
    ai:
        dashscope:
            api-key: ${AI_DASHSCOPE_API_KEY}
        mcp:
            client:
                stdio:
                    servers-configuration: classpath:/mcp-servers-config.json
