/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    alias(libs.plugins.org.springframework.boot)
    application
}

application {
    mainClass.set("org.wesuper.liteai.flywise.stock.StockServerApplication")
}

dependencies {
    implementation(libs.spring.ai.mcp.server.webflux)
    implementation(libs.spring.boot.starter.logging)
    implementation(libs.spring.boot.starter.actuator)
}

description = "omnilink-flywise-stock"

tasks.named<Test>("test") {
    enabled = false
}
